parser/service.go, parser/service_test.go
This fixes a bug where RPCs with multiple in-line options would cause the parser to crash.
=> Support multiple RPC options

_testdata/cloudEndpoints.proto, internal/lexer/lexer.go, parser/field.go, parser/option.go, parser/option_test.go
ref. [Support `option (google.api.http) = {...}` · Issue #22 · yoheimuta/go-protoparser](https://github.com/yoheimuta/go-protoparser/issues/22)
=> Support googleapi style option

parser/enum.go
Change-Id: I0362c20ea26518b152c91e82584a889ca192e350
enum also support reserved, refer to this link:
https://developers.google.com/protocol-buffers/docs/proto3#enum_reserved
=> Support reserved in enum

internal/lexer/scanner/scanner.go, internal/lexer/scanner/scanner_test.go
Change-Id: I4756755c0f684e51a5dffa36a458276ee4e60611
I know it's insane, but other parser allow ident start with underscore...
There is even a test case for this:
https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/name_test.go#L51
=> allow ident start with underscore

internal/lexer/lexer.go, parser/enum.go, parser/enum_test.go, parser/extend.go, parser/extend_test.go, parser/groupField.go, parser/groupField_test.go, parser/message.go, parser/message_test.go, parser/oneof.go, parser/oneof_test.go, parser/service.go, parser/service_test.go
ref. [Accept block followed by semicolon · Issue #30 · yoheimuta/go-protoparser](https://github.com/yoheimuta/go-protoparser/issues/30)
=> feat: Accept a block followed by a semicolon

_testdata/simple.proto, parser/service.go, parser/service_test.go
ref. [Accept block followed by semicolon · Issue #30 · yoheimuta/go-protoparser](https://github.com/yoheimuta/go-protoparser/issues/30)
=> fix: Allow a block followed by semicolon for RPC

_testdata/simple.proto, parser/enum.go, parser/enum_test.go
ref. [Multiline string literals error · Issue #35 · yoheimuta/go-protoparser](https://github.com/yoheimuta/go-protoparser/issues/35)
=> feat: Support multiline string literals

.gitignore, _testdata/simple.proto, internal/lexer/constant.go, internal/lexer/constant_test.go, parser/enum.go, parser/field.go, parser/option.go, parser/option_test.go
Motivated by #35.
Modifies constants lexer to combine series of multiline string literals into a single string literal constant. Removes the code that previously did this specifically for enums, as this now applies to all object types.
=> Allow multiline string literal constants

.gitignore, go.mod
Using internal package paths makes it difficult to contribute without a gomod file, since the importpath does not resolve correctly. This adds the gomod file, to avoid this.
Also, /gitignore the `.idea` folder.
=> Add gomod file for easier contributions

parser/field.go, parser/field_test.go, parser/option.go, parser/option_test.go
The parser reports a lot of protos as broken due to `protoc` being more flexible and forgiving than the official spec suggests.
This PR adds a few of these edge cases, such as:
- Nested support of options
```
additional_bindings {
get: "/v1/users/{user_id}/messages/{message_id}"
}
```
- Alternative syntax for nested options
```
additional_bindings: {
get: "/v1/users/{user_id}/messages/{message_id}"
};
```
- Trailing commas in fields
```
option (field.fields) = {
foo: "data",
bar: "data2",
};
```
Let me know if any of these require extra data. I will be adding tests for these shortly.
=> Improve flexibility of parsing tool

internal/lexer/error.go, internal/lexer/scanner/error.go, internal/lexer/scanner/position.go, internal/lexer/scanner/scanner_test.go, parser/comment.go, parser/enum.go, parser/error.go, parser/extend.go, parser/extensions.go, parser/field.go, parser/groupField.go, parser/import.go, parser/mapField.go, parser/message.go, parser/meta/error.go, parser/meta/meta.go, parser/meta/position.go, parser/oneof.go, parser/option.go, parser/package.go, parser/reserved.go, parser/service.go, parser/syntax.go
This creates a specific error type which can be used for error handling in other tools (eg protolint) instead of the current `fmt.Errorf()` setup.
Before merging, it should be decided whether we expect each component (scanner/lexer/parser) to have its own specific error type, or if one is enough.
The current design uses a single error type, to avoid extra boilerplate on external tools having to check multiple errors, and because they all seem to return the same (or very similar) data. 
Let me know if you have any strong opinions regarding each option.
(And sorry for the large PR, most of it is boilerplate test code that needed editing😅)
=> Expose error data to external tools.

internal/lexer/scanner/comment.go, internal/lexer/scanner/scanner_test.go
ref. [error parsring if file ends with comment _and_ no newline · Issue #49 · yoheimuta/go-protoparser](https://github.com/yoheimuta/go-protoparser/issues/49)
=> feat: Allow a comment without newlines

internal/lexer/lexer.go, internal/lexer/scanner/position.go, parser/option.go, parser/option_test.go
ref. [Parsing breaks on empty fields within options within RPCs · Issue #123 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/123)
=> Fix empty field within option

interpret/unordered/enum.go, interpret/unordered/message.go, interpret/unordered/service.go
I had some difficulty locating a bug in a `.proto` file which was caused parsing to fail, but where our other tools (using protoc) were successfully generating the Go protobuf files, as the error message wasn't clear to me (as an infrequent user). 
I was receiving this error message:
```
invalid MessageBody type &{<nil>} of &{<nil>}
```
But it was unclear to me _which_ Message (in a fairly long proto file) was the source of this. Inevitably it was due to a typo with an extra semicolon at the end of one of the field definitions:
```
repeated string fields = 3 ;;
```
Could we perhaps wrap the error when interpreting Enums, Messages, and Services, with their name so it's easier to find the source of the error? This uses the [error wrapping introduced in Go …
=> Wrap errors from invalid bodies to be more descriptive

internal/lexer/scanner/scanner_test.go, internal/lexer/scanner/token.go, parser/enum.go, parser/enum_test.go, parser/oneof.go, parser/oneof_test.go
ref. [Adapt the parser rule to the official spec updated so far · Issue #57 · yoheimuta/go-protoparser](https://github.com/yoheimuta/go-protoparser/issues/57)
=> Adapt enum and option latest spec

interpret/unordered/enum.go, interpret/unordered/extend.go, interpret/unordered/message.go, interpret/unordered/proto.go, interpret/unordered/service.go
An additional trailing semicolon in the body of a message currently causes `UnorderedInterpret` to fail.
For example, changing the example proto file from the `README`
https://github.com/yoheimuta/go-protoparser/blob/a1aa0a07fe86a183dd06da85e9c5ef6f9a11faa1/README.md?plain=1#L36-L44
to add an additional semicolon somewhere in `outer` (e.g. `option (my_option).a = true;;`) causes the following error to be returned:
```
invalid MessageBody type &{<nil>} of &{<nil>}
```
This PR causes these empty statements to be included on the returned `MessageBody` instead.
-----
While debugging this issue, I also noticed the error message was repeating the same format argument. In the second commit I fixed the error messages so they contain the name of the invalid type and then a representation of the …
=> UnorderedInterpret: handle EmptyStatement in MessageBody 

.circleci/config.yml, .circleci/install_dep.sh, Makefile
ref. https://app.circleci.com/pipelines/github/yoheimuta/go-protoparser/183/workflows/a14f9479-57e3-4733-b9d7-9c75081011b9/jobs/303
```
golang.org/x/sys/execabs
/go/pkg/mod/golang.org/x/sys@v0.0.0-20220502124256-b6088ccd6cba/execabs/execabs_go119.go:11:6: isGo119ErrDot redeclared in this block
previous declaration at /go/pkg/mod/golang.org/x/sys@v0.0.0-20220502124256-b6088ccd6cba/execabs/execabs_go118.go:9:31
note: module requires Go 1.17
make: *** [Makefile:34: dev/install/dep] Error 2
Exited with code exit status 2
```
=> chore: Update go version to v1.18.1

parser/service.go, parser/service_test.go
ref. https://github.com/yoheimuta/protolint/issues/292#issuecomment-1305356269
The parser is supposed to extract `// get the global address table` from the below snippet.
```proto
service SearchService {
rpc GetAll(GetRequest) returns(GetReply) { // get the global address table
option(requestreply.Nats).Subject = "get.addrs";
}
}
```
=> feat: parsing the rpc's trailing comment followed by the left curly brace

parser/meta/error.go
remove copy rights from `meta/error`
=> docs(remove license): copy rights from error

parser/option.go, parser/option_test.go
The spec contains the following regarding optionNames:
option = "option" optionName  "=" constant ";"
optionName = ( ident | bracedFullIdent ) { "." ( ident | bracedFullIdent ) }
bracedFullIdent = "(" ["."] fullIdent ")"
In the previous implementation, only the whole optionName could be in braces, while the spec also allows parts (between dots) to be braced.
An example in the wild on which this would fail is the following snippet, taken from the "Go Opaque API Migration" guide (https://protobuf.dev/reference/go/opaque-migration/):
edition = "2023";
package log;
import "google/protobuf/go_features.proto";
option features.(pb.go).api_level = API_OPAQUE;
message LogEntry { … }
=> Correctly parse bracedFullIdent at all places it can occur in optionName

parser/reserved.go, parser/reserved_test.go
Enhance the parser to support field names separated by whitespace without commas, addressing the parsing error reported in issue #96. Update tests to validate the new parsing behavior for both comma-separated and whitespace-separated field names.
Fixes #96
=> Fix parsing error in buf validate proto file

_testdata/double_semicolon_issue84/main.go, parser/service.go, parser/service_test.go
When encountering a double semicolon in a service option, the parser now correctly creates an EmptyStatement struct for the second semicolon and adds it to the ServiceBody slice. This prevents a nil pointer dereference when the Service.Accept method is called.
The fix was implemented by adding a line to create an EmptyStatement struct in the default case of the switch statement in the parseServiceBody function.
=> Fix #84: Handle double semicolons in service options
